export const functions = {
  'sin': Math.sin,
  'cos': Math.cos,
  'tan': Math.tan,
  'arcsin': Math.asin,
  'arccos': Math.acos,
  'arctan': Math.atan,
  'log': Math.log,
  'ln': Math.log,
  'exp': Math.exp,
  'round': Math.round,
  'floor': Math.floor,
  'ceil': Math.ceil,
  'sqrt': Math.sqrt,
  'abs': Math.abs,
  'random': Math.random,
};
